# Datenstrom Yellow extension settings

Extension: Edit
Version: 1.0.1
Description: Edit your website in a web browser.
Developer: Anna Svensson
Contributor: David Fehrmann, Mark Seuffert
Tag: feature
DownloadUrl: https://github.com/annaesvensson/yellow-edit/archive/refs/heads/main.zip
DocumentationUrl: https://github.com/annaesvensson/yellow-edit
DocumentationLanguage: en, de, sv
Published: 2026-09-25 19:10:27
Status: maintained
system/workers/edit.php: edit.php, create, update
system/workers/edit.css: edit.css, create, update
system/workers/edit.js: edit.js, create, update
system/workers/edit-stack.svg: edit-stack.svg, create, update
content/shared/page-new-default.md: page-new-default.md, create, optional
